[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
filterwarnings =
    ignore::DeprecationWarning
addopts = --json-report --json-report-file=test-report.json --json-report-indent=2
